---
grails:
    profile: rest-api
    codegen:
        defaultPackage: pos.server
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    dbCreate: ''
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
environments:
    development:
        dataSource:
            dbCreate: update
            #url: '${JDBC_URL}'
            url: jdbc:mysql://localhost/siipapx_dev?autoReconnect=false
            #url: jdbc:mysql://10.10.1.229:3306/siipapx_dev?autoReconnect=true
            username: 'root'
            password: 'sys1'
    test:
        dataSource:
            dbCreate: create-drop
            pooled: true
            jmxExport: true
            driverClassName: org.h2.Driver
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: sa
            password:
    production:
        dataSource:
            dbCreate: none
            url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=false
            username: root
            password: sys
            properties:
                maxActive: 10
                maxIdle: 10
                minIdle: 3
                initialSize: 3
                minEvictableIdleTimeMillis: 1800000
                timeBetweenEvictionRunsMillis: 1800000
                numTestsPerEvictionRun: 3
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                maxWait: 10000
                validationQuery: 'SELECT 1'
                validationQueryTimeout: 3
                validationInterval: 15000
---
#grails:
#      plugin:
#          springsecurity:
#              userLookup:
#                  userDomainClassName: sx.security.User
#                  authorityJoinClassName: sx.security.UserRole
#              authority:
#                  className: sx.security.Role
#              filterChain:
#                  chainMap:
#                      -
#                          pattern: /assets/**
#                          filters: none
#                      -
#                          pattern: /**/js/**
#                          filters: none
#                      -
#                          pattern: /**/css/**
#                          filters: none
#                      -
#                          pattern: /**/images/**
#                          filters: none
#                      - # Stateless chain
#                          pattern: /api/**
#                          filters: JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter
#                      - # Traditional Chain
#                          pattern: /**
#                          filters: JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter
#                  controllerAnnotations:
#                      staticRules:
#                          -
#                              pattern: /
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /error
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /index
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /index.gsp
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /shutdown
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /assets/**
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /**/js/**
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /**/css/**
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /**/images/**
#                              access:
#                                  - permitAll
#                          -
#                              pattern: /**/favicon.ico/**
#                              access:
#                                  - permitAll
---
server:
  port: 9090
  contextPath: /siipapx
---
grails:
    cors:
        enabled: true